# Configuración de producción para AWS
# Este archivo debe ser usado en lugar de application-prod.yml

server:
  port: 8700

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3306}/${DB_NAME:ecommerce_prod_db}?useSSL=true&serverTimezone=UTC
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        use_sql_comments: true
        format_sql: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    ssl: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

logging:
  level:
    org:
      hibernate:
        SQL: INFO
      springframework:
        web: INFO
        data: INFO
      boot:
        autoconfigure:
          data:
            rest: INFO
            jpa: INFO
            orm: INFO
  appenders:
    - type: console
    - type: file
      file: /var/log/app/user-service.log
      rollingPolicy:
        type: size
        maxFileSize: 10MB
        maxHistory: 10
