apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: selimhorri/order-service-ecommerce-boot:0.1.0
          ports:
            - containerPort: 8300
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_ZIPKIN_BASE_URL
              value: http://zipkin:9411
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://cloud-config:9296/
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://cloud-config:9296
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://service-discovery:8761/eureka/
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE
              value: http://service-discovery:8761/eureka/
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            - name: EUREKA_INSTANCE_NON_SECURE_PORT
              value: "8300"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ecommerce
spec:
  selector:
    app: order-service
  ports:
    - name: http
      port: 8300
      targetPort: 8300
      nodePort: 30830
  type: NodePort
