apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-client
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-client
  template:
    metadata:
      labels:
        app: proxy-client
    spec:
      containers:
        - name: proxy-client
          image: selimhorri/proxy-client-ecommerce-boot:0.1.0
          ports:
            - containerPort: 8900
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_ZIPKIN_BASE_URL
              value: http://zipkin:9411
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://cloud-config:9296/
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://cloud-config:9296
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "false"
            # Precedencia: ENV/sistema debe pisar config remota
            - name: SPRING_CLOUD_CONFIG_ALLOW_OVERRIDE
              value: "true"
            - name: SPRING_CLOUD_CONFIG_OVERRIDE_SYSTEM_PROPERTIES
              value: "true"
            - name: SPRING_CLOUD_CONFIG_OVERRIDE_NONE
              value: "false"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://service-discovery:8761/eureka/
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            # Registrar con IP del Pod en Eureka
            - name: EUREKA_INSTANCE_NON_SECURE_PORT
              value: "8900"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_INSTANCE_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: EUREKA_INSTANCE_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-client
  namespace: ecommerce
spec:
  selector:
    app: proxy-client
  ports:
    - name: http
      port: 8900
      targetPort: 8900
      nodePort: 30900
  type: NodePort