apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: selimhorri/user-service-ecommerce-boot:0.1.0
          ports:
            - containerPort: 8700
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_ZIPKIN_BASE_URL
              value: http://zipkin:9411
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://cloud-config:9296/
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://cloud-config:9296
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "false"
            # Precedencia: ENV/sistema debe pisar config remota
            - name: SPRING_CLOUD_CONFIG_ALLOW_OVERRIDE
              value: "true"
            - name: SPRING_CLOUD_CONFIG_OVERRIDE_SYSTEM_PROPERTIES
              value: "true"
            - name: SPRING_CLOUD_CONFIG_OVERRIDE_NONE
              value: "false"
            # Forzar defaultZone -> service-discovery
            - name: SPRING_APPLICATION_JSON
              value: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://service-discovery:8761/eureka/"}}}}'
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://service-discovery:8761/eureka/
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            # Registrar con la IP del Pod en Eureka (no localhost)
            - name: EUREKA_INSTANCE_NON_SECURE_PORT
              value: "8700"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_INSTANCE_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: EUREKA_INSTANCE_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: ecommerce
spec:
  selector:
    app: user-service
  ports:
    - name: http
      port: 8700
      targetPort: 8700
      nodePort: 30700
  type: NodePort